{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello-oke.serviceAccountName" . }}
  labels:
    {{- include "hello-oke.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
[opc@jenkins templates]$ cat service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-oke.fullname" . }}
  labels:
    {{- include "hello-oke.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-oke.selectorLabels" . | nindent 4 }}
